#
# lit-embed example config
#

# base output directory
out_dir: "/data/lit-embed"

# random seed
random_seed: 321

# development mode; if enabled, only a subset of articles are analyzed
dev_mode:
  enabled: false
  num_articles: 1000

# word frequency / tf-idf settings
word_freq:
  # minimum/maximum number or proportion of articles which must include a term for it to
  # be used in matrix generation
  min_df: 10
  max_df: 0.6
  # maximum number of features to keep
  max_features: 1000

tokenization:
  lemmatize: true
  min_length: 2

# clustering parameters (mini-batch kmeans)
clustering:
  num_clusters: 10
  batch_size: 8192

# t-SNE article visualization
tsne:
  subsample: 5000
