#
# lit-embed example config
#

# base output directory
out_dir: "/data/lit-embed"

# random seed
random_seed: 321

# development mode; if enabled, only a subset of articles are analyzed
dev_mode:
  enabled: false
  num_articles: 100000

# arxiv-related settings
arxiv:
  # number of chunks to split dataset into for processing
  num_chunks: 100

# pubmed-related settings
pubmed:
  # start and end number for daily updates
  # https://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/
  updates_start: 1115
  updates_end: 1191

# factors to use to decide whether to exclude an article from analysis
exclude_articles:
  missing_abstract: true
  missing_title: true

# word frequency / tf-idf settings
word_freq:
  # minimum/maximum number or proportion of articles which must include a term for it to
  # be used in word-freq/tf-df matrices
  min_df: 10
  max_df: 0.6
  # maximum number of features to keep
  max_features: 1000

tokenization:
  min_length: 2

# clustering parameters (mini-batch kmeans)
clustering:
  articles:
    num_clusters: 20
    batch_size: 8192
  topics:
    num_clusters: 15
    batch_size: 8192

# t-SNE settings
tsne:
  articles:
    num: 10000
    metric: 'cosine'
    perplexity: 30
  topics:
    num: 10000
    metric: 'cosine'
    perplexity: 30
    max_articles: 10000

# UMAP settings
umap:
  articles:
    num: 500000
    densmap: true
    n_neighbors: 25
    min_dist: 0.1
    metric: 'cosine'
  topics:
    num: 10000
    densmap: true
    n_neighbors: 25
    min_dist: 0.1
    metric: 'cosine'

# plot settings
plots:
  scatterplot:
    max_points: 10000
    width: 16
    height: 12
    size: 14
  datashader:
    max_points: 500000
    width: 1000
    height: 1000
