#
# lit-embed example config
#

# base output directory
out_dir: "/data/lit-embed"

# random seed
random_seed: 321

# development mode; if enabled, only a subset of articles are analyzed
dev_mode:
  enabled: false
  num_articles: 100000

# arxiv-related settings
arxiv:
  # number of chunks to split dataset into for processing
  num_chunks: 100

# pubmed-related settings
pubmed:
  # start and end number for annual files
  # https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/
  annual_start: 1000
  annual_end: 1114
  # start and end number for daily updates
  # https://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/
  updates_start: 1115
  updates_end: 1244

# factors to use to decide whether to exclude an article from analysis
exclude_articles:
  missing_abstract: true
  missing_title: true

# parameters to use for co-citation validation test set generation?
# for now, just choosing articles at random to compare, and keep number of test sets
# fixed to simplify pipeline
validation:
  # limit analysis to articles that have at least this many mapped citations
  min_citations: 20
  # random seed & size for test sets to be generated
  test_sets:
    set1:
      topic: 'myeloma'
      n: 1000
      seed: 2837
    set2:
      topic: 'malaria'
      n: 1000
      seed: 9283
    set3:
      topic: 'single-cell'
      n: 1000
      seed: 5823

# word frequency / tf-idf settings
word_freq:
  # minimum/maximum number or proportion of articles which must include a term for it to
  # be used in word-freq/tf-df matrices
  min_df: 0.001
  max_df: 0.6
  # datatype
  dtype: 'float64'
  # number of frequent (word-freq) or top-scoring (tf-idf) features to use for embeddings
  num_features: 768
  # for tf-idf feature selection, relative contribution of mean tf-idf vs. idf;
  # value should be between "0" and "1", with values closer to "1" corresponding to a
  # larger contribution from the mean tf-idf value for each term
  alpha: 0.8

tokenization:
  min_length: 3

# maximum count contribution of a single article when computing moderated residual IDF
# scores
word_stats:
  moderated_ridf_max_count: 5

# clustering parameters
#  articles: mini-batch k-means
#  embedding_columns: agglomerative hclust
clustering:
  articles:
    num_clusters: 20
    batch_size: 8192
  embedding_columns:
    num_clusters: 20
    linkage: 'average'
    affinity: 'l1'
    max_articles: 10000

# t-SNE settings
tsne:
  articles:
    num: 5000
    metric: 'cosine'
    perplexity: 30
  embedding_columns:
    num: 5000
    metric: 'cosine'
    perplexity: 30
    max_articles: 10000

# UMAP settings
umap:
  articles:
    num: 500000
    densmap: false
    n_neighbors: 25
    min_dist: 0.1
    metric: 'cosine'
  embedding_columns:
    num: 10000
    densmap: true
    n_neighbors: 20 
    min_dist: 0.1
    metric: 'cosine'

# plot settings
plots:
  scatterplot:
    max_points: 10000
    width: 16
    height: 12
    size: 14
  datashader:
    max_points: 1000000
    width: 1000
    height: 1000
